<?php
/**
 * Created by PhpStorm.
 * User: yifanfengshun
 * Date: 2016/11/14
 * Time: 下午3:35
 */

namespace Home\Controller;


class DividendController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        import("Class.RedisObject");
        $redisObj = new \RedisObject();
        $key = md5("userbonus".session("SESSION_ID"));
        if($redisObj->exists($key))
        {
            $userBonusInfo = json_decode($redisObj->_get($key), true);
        }
        else
        {
            $userBonusInfo = M("user_bonus")->where(array('userid'=>session("SESSION_ID")))->find();
            $redisObj->_set($key,json_encode($userBonusInfo));
        }
        $bonuslevel = $userBonusInfo["bonus_level"];
        if(bccomp($bonuslevel,12.7,2)==-1)
        {
            redirect("/index");
        }
    }

    public function index()
    {
        $this->menu = "proxy";
        $this->managermenu = 'proxy';
        $this->proxymanager = 'dividend';

        //判断按钮是否显示
        $stime = mktime(3,0,0,date("m"),1,date("Y"));
        $mtime = mktime(3,0,0,date("m"),16,date("Y"));
        $etime = mktime(3,0,0,date("m")+1,1,date("Y"));
        $time = time();

        if($time>$stime && $time<$mtime){
            $_s1 = mktime(3,0,0,date("m")-1,16,date("Y"));
            $_s2 = mktime(3,0,0,date("m")+1,1,date("Y"));
        } else if($time>$mtime && $time<$etime){
            $_s1 = mktime(3,0,0,date("m"),1,date("Y"));
            $_s2 = mktime(3,0,0,date("m"),16,date("Y"));
        }

        $user_hongli = M("user_hongli");
        $user_hongli_count = M("user_hongli_count");
        if($time>$stime && $time<$mtime){
            //判断上半个月的分红是否已经领取
            $map["userid"] = session("SESSION_ID");
            $map["_string"] = "starttime>=".$_s1." and endtime<=".$_s2;
            $map["status"] = 0;
            $res = $user_hongli->where($map)->select();
            if(empty($res)){
                $this->button = false;
            } else {
                $showtime1 = mktime(12,0,0,date("m"),1,date("Y"));
                $showtime2 = mktime(0,0,0,date("m"),16,date("Y"));
                if($time>=$showtime1 && $time<=$showtime2)
                    $this->button = true;
            }
        }
        if($time>$mtime && $mtime<$etime){
            //判断下半个月的分红是否已经领取
            $map["userid"] = session("SESSION_ID");
            $map["_string"] = "starttime>=".$_s1." and endtime<=".$_s2;
            $map["status"] = 0;
            $res = $user_hongli->where($map)->select();
            if(empty($res)){
                $this->button = false;
            } else {
                $showtime1 = mktime(12,0,0,date("m"),16,date("Y"));
                $showtime2 = mktime(0,0,0,date("m")+1,1,date("Y"));
                if($time>=$showtime1 && $time<=$showtime2)
                    $this->button = true;
            }
        }
        //前站时间的显示
        if($time>$stime && $time<$mtime){
            $this->starttime = date("Y-m-d H:i:s",mktime(3,0,0,date("m"),1,date("Y")));
            $this->endtime = date("Y-m-d H:i:s",mktime(3,0,0,date("m"),16,date("Y")));
        }
        if($time>$mtime && $time<$etime){
            $this->starttime = date("Y-m-d H:i:s",mktime(3,0,0,date("m"),16,date("Y")));
            $this->endtime = date("Y-m-d H:i:s",mktime(3,0,0,date("m")+1,1,date("Y")));
        }
        //未结算盈亏
        $_map["userid"] = session("SESSION_ID");
        $_map["status"] = 0;
        $map["_string"] = "starttime>=".$_s1." and endtime<=".$_s2;
        $totalyingkui = $user_hongli->where($_map)->sum("totalyingkui");
        if($totalyingkui<0){
            $this->yk = sprintf("%.4f",$totalyingkui/100000);
        } else {
            $this->yk = 0;
        }
        if($this->yk==0){
            $this->button = false;
        }
        //当前分红金额
        $hongli = $user_hongli->where($_map)->sum("hongli");
        if($hongli<0) {
            $hongli = abs($hongli);
            $this->hl = sprintf("%.4f", $hongli / 100000);
        } else {
            $this->hl = 0;
        }
        //已结算的盈亏
        unset($_map["status"]);
        $_map["status"] = 1;
        $yijie_totalyingkui = $user_hongli->where($_map)->sum("totalyingkui");
        if($yijie_totalyingkui<0){
            $this->yjyk = sprintf("%.4f",$yijie_totalyingkui/100000);
        } else {
            $this->yjyk = 0.0000;
        }

        //已结算的分红
        $yijie_hongli = $user_hongli->where($_map)->sum("hongli");
        if($yijie_hongli<0) {
            $yijie_hongli = abs($yijie_hongli);
            $this->yjhl = sprintf("%.4f", $yijie_hongli / 100000);
        } else {
            $this->yjhl = 0.0000;
        }
        //红利结算次数
        $res_count = $user_hongli_count->where(array("userid"=>session("SESSION_ID")))->find();
        if(!empty($res_count)){
            $this->count = $res_count["count"];
        } else {
            $this->count = 0;
        }

        //总关闭按钮
        $switch = M("lottery_switch")->where(array("lottery_id"=>20))->getField("switch");
        if($switch=="close"){
            $this->button = false;
        }
        $this->display();
    }

    public function getDividend()
    {
        $uid = session("SESSION_ID");
        $username = session("SESSION_NAME");
        $ip = ip2long(get_client_ip());
        $MD5STR = md5($username.$uid.$ip."lingquhongli");
        //防止重复提交
        import("Class.RedisObject");
        $redisObj = new \RedisObject();
        if($redisObj->_get($MD5STR)){
            echo "请您慢点，先喝杯茶";
            exit();
        }else{
            $redisObj->_set($MD5STR,1);
            $redisObj->_expire($MD5STR,10);
        }


        $stime = mktime(3,0,0,date("m"),1,date("Y"));
        $mtime = mktime(3,0,0,date("m"),16,date("Y"));
        $etime = mktime(3,0,0,date("m")+1,1,date("Y"));
        $time = time();


        if($time>$stime && $time<$mtime){
            $_s1 = mktime(3, 0, 0, date("m") - 1, 16, date("Y"));
            $_s2 = mktime(3, 0, 0, date("m"), 1, date("Y"));
        } else if($time>$mtime && $time<$etime){
            $_s1 = mktime(3,0,0,date("m"),1,date("Y"));
            $_s2 = mktime(3,0,0,date("m"),16,date("Y"));
        }

        $user_hongli = M("user_hongli");
        $user_hongli_count = M("user_hongli_count");
        $user = M("user");
        $accounts_change = M("accounts_change");
        if($time>$stime && $time<$mtime){
            //判断下半个月的分红是否已经领取
            $map["userid"] = session("SESSION_ID");
            $map["_string"] = "starttime>=".$_s1." and endtime<=".$_s2;
            $map["status"] = 0;
            $res = $user_hongli->where($map)->select();
            if(empty($res)){
                echo "该次分红已经领取";
                exit();
            } else {

                $showtime1 = mktime(12,0,0,date("m"),1,date("Y"));
                $showtime2 = mktime(0,0,0,date("m"),16,date("Y"));
                if($time>=$showtime1 && $time<=$showtime2){
                    $hongli = $user_hongli->where($map)->sum("hongli");
                    if($hongli>=0){
                        echo "无分红数据";
                        exit();
                    }
                    //红利加入用户账户
                    $hongli = abs($hongli);
                    $userinfo = $user->where(array("id"=>session("SESSION_ID")))->find();
                    $beforeMoney = $userinfo["cur_account"];
                    $nowMoney = $beforeMoney+$hongli;
                    //更新账户金额
                    $user->where(array("id"=>session("SESSION_ID")))->save(array("cur_account"=>$nowMoney));
                    //添加帐变
                    $account_data = array(
                        "accounts_type" => 25,
                        "buy_record_id" => 0,
                        "change_amount" => $hongli,
                        "userid" => $userinfo["id"],
                        "username" => $userinfo["username"],
                        "parent_id" => $userinfo["parent_id"],
                        "parent_path" => $userinfo["parent_path"],
                        "cur_account" => $nowMoney,
                        "serial_number" => 0,
                        "runner_id" => $userinfo["id"],
                        "runner_name" => $userinfo["username"],
                        "change_time" => time(),
                        "is_addto" => 0,
                        "remark"    => "领取分红",
                        "buy_type_id" => 0,
                        "lottery_id" => 0,
                        "lottery_number_id" => 0,
                        "yuan" => 0
                    );
                    $account_id = $accounts_change->add($account_data);
                    import("Class.XDeode");
                    $_xDe=new \XDeode();
                    //更新该条账变的账变编号
                    $achange_num = strtoupper($_xDe->encode($account_id));
                    $accounts_change->where(array("id" =>$account_id))->save(array("achange_num"=>$achange_num));

                    //更新分红表的状态
                    $user_hongli->where($map)->save(array("status"=>1));

                    //更新分红的次数
                    $count_res = $user_hongli_count->where(array("userid"=>session("SESSION_ID")))->find();
                    if(!empty($count_res)){
                        $user_hongli_count->where(array("userid"=>session("SESSION_ID")))->setinc("count",1);
                    } else {
                        $user_hongli_count->add(array("userid"=>session("SESSION_ID"),"time"=>time(),"count"=>1));
                    }

                    echo "领取分红成功";
                    exit();

                } else {
                    echo "未到领取时间";
                    exit();
                }

            }
        }
        if($time>$mtime && $mtime<$etime){
            //判断上半个月的分红是否已经领取
            $map["userid"] = session("SESSION_ID");
            $map["_string"] = "starttime>=".$_s1." and endtime<=".$_s2;
            $map["status"] = 0;
            $res = $user_hongli->where($map)->select();
            if(empty($res)){
                echo "该次分红已经领取";
                exit();
            } else {
                $showtime1 = mktime(14,0,0,date("m"),16,date("Y"));
                $showtime2 = mktime(0,0,0,date("m")+1,1,date("Y"));
                if($time>=$showtime1 && $time<=$showtime2){
                    $hongli = $user_hongli->where($map)->sum("hongli");
                    if($hongli>=0){
                        echo "无分红数据";
                        exit();
                    }
                    //红利加入用户账户
                    $hongli = abs($hongli);
                    $userinfo = $user->where(array("id"=>session("SESSION_ID")))->find();
                    $beforeMoney = $userinfo["cur_account"];
                    $nowMoney = $beforeMoney+$hongli;
                    //更新账户金额
                    $user->where(array("id"=>session("SESSION_ID")))->save(array("cur_account"=>$nowMoney));
                    //添加帐变
                    $account_data = array(
                        "accounts_type" => 25,
                        "buy_record_id" => 0,
                        "change_amount" => $hongli,
                        "userid" => $userinfo["id"],
                        "username" => $userinfo["username"],
                        "parent_id" => $userinfo["parent_id"],
                        "parent_path" => $userinfo["parent_path"],
                        "cur_account" => $nowMoney,
                        "serial_number" => 0,
                        "runner_id" => $userinfo["id"],
                        "runner_name" => $userinfo["username"],
                        "change_time" => time(),
                        "is_addto" => 0,
                        "remark"    => "领取分红",
                        "buy_type_id" => 0,
                        "lottery_id" => 0,
                        "lottery_number_id" => 0,
                        "yuan" => 0
                    );
                    $account_id = $accounts_change->add($account_data);
                    import("Class.XDeode");
                    $_xDe=new \XDeode();
                    //更新该条账变的账变编号
                    $achange_num = strtoupper($_xDe->encode($account_id));
                    $accounts_change->where(array("id" =>$account_id))->save(array("achange_num"=>$achange_num));

                    //更新分红表的状态
                    $user_hongli->where($map)->save(array("status"=>1));

                    //更新分红的次数
                    $count_res = $user_hongli_count->where(array("userid"=>session("SESSION_ID")))->find();
                    if(!empty($count_res)){
                        $user_hongli_count->where(array("userid"=>session("SESSION_ID")))->setinc("count",1);
                    } else {
                        $user_hongli_count->add(array("userid"=>session("SESSION_ID"),"time"=>time(),"count"=>1));
                    }

                    echo "领取分红成功";
                    exit();
                }

            }
        }  else {
            echo "未到领取时间";
            exit();
        }
    }

}